# Generated by Django 5.1.5 on 2025-08-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileEditLog',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='type',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='signinType',
            field=models.IntegerField(choices=[(1, 'Sign In'), (2, 'Sign Out')], default=0),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='updateType',
            field=models.IntegerField(choices=[(1, 'Update Password'), (2, 'Update Profile Info')], default=0),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Success'), (2, 'Fail')], default=1),
        ),
    ]
