# Generated by Django 5.2.4 on 2025-08-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status_value',
            field=models.TextField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Finished', 'Finished')], default='Available', null=True),
        ),
    ]
