# Generated by Django 5.2.4 on 2025-08-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0002_alter_accountdetail_id'),
        ('travella', '0002_alter_package_transportation_alter_photo_path_and_more'),
    ]

    operations = [
    ]
