# Generated by Django 5.2.4 on 2025-08-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0002_rename_createdby_package_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='status',
        ),
        migrations.AddField(
            model_name='packagedata',
            name='status',
            field=models.TextField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Finished', 'Finished')], default='Available', null=True),
        ),
    ]
