# Generated by Django 5.2.5 on 2025-08-21 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0002_alter_package_transportation_alter_photo_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to=settings.AUTH_USER_MODEL),
        ),
    ]
