# Generated by Django 5.2.4 on 2025-09-02 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0003_alter_accountdetail_account_alter_booking_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='accesslog',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
