# Generated by Django 5.2.5 on 2025-08-21 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0003_alter_accountdetail_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
