# Generated by Django 5.2.4 on 2025-08-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0003_remove_package_status_packagedata_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='createdBy',
            new_name='created_by',
        ),
    ]
