# Generated by Django 5.2.4 on 2025-09-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0004_booking_booking_code_alter_accesslog_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernotification',
            name='booking_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
