# Generated by Django 5.2.4 on 2025-09-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0005_customernotification_booking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customernotification',
            name='booking_code',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='code',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
