# Generated by Django 5.2.4 on 2025-09-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0006_remove_customernotification_booking_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='path',
            new_name='image',
        ),
    ]
