# Generated by Django 5.2.4 on 2025-08-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0006_alter_paymenttype_key_alter_photo_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Reserved'), (3, 'Cancelled'), (4, 'Requesting')], default=1),
        ),
    ]
