# Generated by Django 5.2.5 on 2025-09-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
