# Generated by Django 5.1.5 on 2025-09-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0007_rename_path_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
