# Generated by Django 5.2.4 on 2025-08-27 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='booking',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='travella.paymentrequest'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
