# Generated by Django 5.2.4 on 2025-08-27 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0008_remove_reservation_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='travella.booking'),
        ),
    ]
