# Generated by Django 5.1.5 on 2025-09-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0008_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunding',
            name='status',
            field=models.IntegerField(choices=[(1, 'Processing'), (2, 'Refunded')], default=1),
        ),
    ]
