# Generated by Django 5.2.4 on 2025-08-28 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0009_reservation_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='refund_cover_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Payment Rejected'), (2, 'Payment Reserved'), (3, 'Booking Cancelled')])),
                ('image', models.ImageField(upload_to='noti/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
