# Generated by Django 5.2.4 on 2025-08-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0010_reservation_refund_cover_date_customernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='auto_cancel_date',
            field=models.DateTimeField(null=True),
        ),
    ]
