# Generated by Django 5.2.4 on 2025-09-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0010_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
