# Generated by Django 5.2.4 on 2025-08-28 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0011_booking_auto_cancel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernotification',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
