# Generated by Django 5.2.4 on 2025-09-07 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0011_chatmessage_is_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Booking Limit'), (2, 'Payment Limit')])),
                ('counts', models.IntegerField(default=10)),
                ('expire_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
