# Generated by Django 5.2.4 on 2025-08-29 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0012_customernotification_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='image',
            field=models.ImageField(null=True, upload_to='itineraries/'),
        ),
    ]
