# Generated by Django 5.2.4 on 2025-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0013_itinerary_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='image',
            field=models.ImageField(null=True, upload_to='public/itineraries/'),
        ),
    ]
