# Generated by Django 5.2.4 on 2025-08-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0014_alter_itinerary_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileEditLog',
        ),
        migrations.RemoveField(
            model_name='accesslog',
            name='type',
        ),
        migrations.AddField(
            model_name='accesslog',
            name='access_type',
            field=models.IntegerField(choices=[(1, 'Sign In'), (2, 'Sign Up'), (3, 'Sign Out'), (4, 'Update Password'), (5, 'Update Profile Info')], null=True),
        ),
    ]
