# Generated by Django 5.2.4 on 2025-09-01 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0015_delete_profileeditlog_remove_accesslog_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refunding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('refund_phone', models.CharField(max_length=15)),
                ('booking', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='travella.booking')),
                ('refund_payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refundings', to='travella.paymenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
