# Generated by Django 5.2.4 on 2025-09-01 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0016_refunding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunding',
            name='refund_payment_type',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='travella.booking'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='travella.paymentrequest'),
        ),
    ]
