# Generated by Django 5.2.4 on 2025-09-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0017_alter_refunding_refund_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='photo',
            field=models.ImageField(null=True, upload_to='account/profile/'),
        ),
    ]
