# Generated by Django 5.2.5 on 2025-09-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0008_alter_accountdetail_photo'),
        ('travella', '0017_alter_refunding_refund_payment_type_and_more'),
    ]

    operations = [
    ]
