# Generated by Django 5.2.5 on 2025-09-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0018_merge_20250902_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
