# Generated by Django 5.2.4 on 2025-09-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travella', '0018_alter_accountdetail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernotification',
            name='related_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
